services:
  - type: web
    name: gc-questionnaire
    env: python
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: HR_ACCESS_CODE
        sync: false
